apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-exporter
  namespace: monitoring
spec:
  template:
    metadata:
      annotations:
        # Annotations so this pod is scrapped by the scalyr agent
        prometheus.io/port:                            "9100"
        k8s.monitor.config.scalyr.com/scrape:          "true"
        k8s.monitor.config.scalyr.com/scrape_interval: "60"
